version: "3.1"
services:
  fastapi:
    build: api
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-tier
    volumes:
      - url-persistence:/app/data/
      
    

  
 
volumes:
  url-persistence:
networks:
  app-tier:
    driver: bridge
