version: "3.1"
services:
  fastapi:
    build: api
    environment:     
      USER: '${MONGODB_USERNAME:-mongodb}'
      PASSWORD: '${MONGODB_PASSWORD:-12345678}'
      DB: '${MONGODB_DATABASE:-db}'
      HOSTNAME: '${HOSTNAME:-mongodb}'
    ports:
      - "8080:80"
    networks:
      - app-tier
    

  
 
  
networks:
  app-tier:
    driver: bridge
